/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainUserRouteImport } from './routes/_main/user'
import { Route as MainTypeRouteImport } from './routes/_main/type'
import { Route as MainTeachersRouteImport } from './routes/_main/teachers'
import { Route as MainSettingsRouteImport } from './routes/_main/settings'
import { Route as MainPartnersRouteImport } from './routes/_main/partners'
import { Route as MainMediaRouteImport } from './routes/_main/media'
import { Route as MainLinksRouteImport } from './routes/_main/links'
import { Route as MainLeadershipRouteImport } from './routes/_main/leadership'
import { Route as MainFeedbacksRouteImport } from './routes/_main/feedbacks'
import { Route as MainFaqsRouteImport } from './routes/_main/faqs'
import { Route as MainEventRouteImport } from './routes/_main/event'
import { Route as MainDocumentsRouteImport } from './routes/_main/documents'
import { Route as MainCourseRouteImport } from './routes/_main/course'
import { Route as MainCategoriesRouteImport } from './routes/_main/categories'
import { Route as MainBannerRouteImport } from './routes/_main/banner'
import { Route as MainAboutRouteImport } from './routes/_main/about'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'
import { Route as MainPagesIndexRouteImport } from './routes/_main/pages/index'
import { Route as MainNewsIndexRouteImport } from './routes/_main/news/index'
import { Route as MainMenuIndexRouteImport } from './routes/_main/menu/index'
import { Route as MainPagesCreateRouteImport } from './routes/_main/pages/create'
import { Route as MainNewsCreateRouteImport } from './routes/_main/news/create'
import { Route as MainPagesUpdateIdRouteImport } from './routes/_main/pages/update/$id'
import { Route as MainNewsUpdateIdRouteImport } from './routes/_main/news/update/$id'
import { Route as MainMenuViewIdRouteImport } from './routes/_main/menu/view/$id'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUserRoute = MainUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTypeRoute = MainTypeRouteImport.update({
  id: '/type',
  path: '/type',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainTeachersRoute = MainTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainSettingsRoute = MainSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPartnersRoute = MainPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMediaRoute = MainMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLinksRoute = MainLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainLeadershipRoute = MainLeadershipRouteImport.update({
  id: '/leadership',
  path: '/leadership',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFeedbacksRoute = MainFeedbacksRouteImport.update({
  id: '/feedbacks',
  path: '/feedbacks',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainFaqsRoute = MainFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainEventRoute = MainEventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainDocumentsRoute = MainDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCourseRoute = MainCourseRouteImport.update({
  id: '/course',
  path: '/course',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesRoute = MainCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainBannerRoute = MainBannerRouteImport.update({
  id: '/banner',
  path: '/banner',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainAboutRoute = MainAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRouteRoute,
} as any)
const MainPagesIndexRoute = MainPagesIndexRouteImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNewsIndexRoute = MainNewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMenuIndexRoute = MainMenuIndexRouteImport.update({
  id: '/menu/',
  path: '/menu/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPagesCreateRoute = MainPagesCreateRouteImport.update({
  id: '/pages/create',
  path: '/pages/create',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNewsCreateRoute = MainNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainPagesUpdateIdRoute = MainPagesUpdateIdRouteImport.update({
  id: '/pages/update/$id',
  path: '/pages/update/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainNewsUpdateIdRoute = MainNewsUpdateIdRouteImport.update({
  id: '/news/update/$id',
  path: '/news/update/$id',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMenuViewIdRoute = MainMenuViewIdRouteImport.update({
  id: '/menu/view/$id',
  path: '/menu/view/$id',
  getParentRoute: () => MainRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/about': typeof MainAboutRoute
  '/banner': typeof MainBannerRoute
  '/categories': typeof MainCategoriesRoute
  '/course': typeof MainCourseRoute
  '/documents': typeof MainDocumentsRoute
  '/event': typeof MainEventRoute
  '/faqs': typeof MainFaqsRoute
  '/feedbacks': typeof MainFeedbacksRoute
  '/leadership': typeof MainLeadershipRoute
  '/links': typeof MainLinksRoute
  '/media': typeof MainMediaRoute
  '/partners': typeof MainPartnersRoute
  '/settings': typeof MainSettingsRoute
  '/teachers': typeof MainTeachersRoute
  '/type': typeof MainTypeRoute
  '/user': typeof MainUserRoute
  '/': typeof MainIndexRoute
  '/news/create': typeof MainNewsCreateRoute
  '/pages/create': typeof MainPagesCreateRoute
  '/menu': typeof MainMenuIndexRoute
  '/news': typeof MainNewsIndexRoute
  '/pages': typeof MainPagesIndexRoute
  '/menu/view/$id': typeof MainMenuViewIdRoute
  '/news/update/$id': typeof MainNewsUpdateIdRoute
  '/pages/update/$id': typeof MainPagesUpdateIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/about': typeof MainAboutRoute
  '/banner': typeof MainBannerRoute
  '/categories': typeof MainCategoriesRoute
  '/course': typeof MainCourseRoute
  '/documents': typeof MainDocumentsRoute
  '/event': typeof MainEventRoute
  '/faqs': typeof MainFaqsRoute
  '/feedbacks': typeof MainFeedbacksRoute
  '/leadership': typeof MainLeadershipRoute
  '/links': typeof MainLinksRoute
  '/media': typeof MainMediaRoute
  '/partners': typeof MainPartnersRoute
  '/settings': typeof MainSettingsRoute
  '/teachers': typeof MainTeachersRoute
  '/type': typeof MainTypeRoute
  '/user': typeof MainUserRoute
  '/': typeof MainIndexRoute
  '/news/create': typeof MainNewsCreateRoute
  '/pages/create': typeof MainPagesCreateRoute
  '/menu': typeof MainMenuIndexRoute
  '/news': typeof MainNewsIndexRoute
  '/pages': typeof MainPagesIndexRoute
  '/menu/view/$id': typeof MainMenuViewIdRoute
  '/news/update/$id': typeof MainNewsUpdateIdRoute
  '/pages/update/$id': typeof MainPagesUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_main/about': typeof MainAboutRoute
  '/_main/banner': typeof MainBannerRoute
  '/_main/categories': typeof MainCategoriesRoute
  '/_main/course': typeof MainCourseRoute
  '/_main/documents': typeof MainDocumentsRoute
  '/_main/event': typeof MainEventRoute
  '/_main/faqs': typeof MainFaqsRoute
  '/_main/feedbacks': typeof MainFeedbacksRoute
  '/_main/leadership': typeof MainLeadershipRoute
  '/_main/links': typeof MainLinksRoute
  '/_main/media': typeof MainMediaRoute
  '/_main/partners': typeof MainPartnersRoute
  '/_main/settings': typeof MainSettingsRoute
  '/_main/teachers': typeof MainTeachersRoute
  '/_main/type': typeof MainTypeRoute
  '/_main/user': typeof MainUserRoute
  '/_main/': typeof MainIndexRoute
  '/_main/news/create': typeof MainNewsCreateRoute
  '/_main/pages/create': typeof MainPagesCreateRoute
  '/_main/menu/': typeof MainMenuIndexRoute
  '/_main/news/': typeof MainNewsIndexRoute
  '/_main/pages/': typeof MainPagesIndexRoute
  '/_main/menu/view/$id': typeof MainMenuViewIdRoute
  '/_main/news/update/$id': typeof MainNewsUpdateIdRoute
  '/_main/pages/update/$id': typeof MainPagesUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/login'
    | '/about'
    | '/banner'
    | '/categories'
    | '/course'
    | '/documents'
    | '/event'
    | '/faqs'
    | '/feedbacks'
    | '/leadership'
    | '/links'
    | '/media'
    | '/partners'
    | '/settings'
    | '/teachers'
    | '/type'
    | '/user'
    | '/'
    | '/news/create'
    | '/pages/create'
    | '/menu'
    | '/news'
    | '/pages'
    | '/menu/view/$id'
    | '/news/update/$id'
    | '/pages/update/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/login'
    | '/about'
    | '/banner'
    | '/categories'
    | '/course'
    | '/documents'
    | '/event'
    | '/faqs'
    | '/feedbacks'
    | '/leadership'
    | '/links'
    | '/media'
    | '/partners'
    | '/settings'
    | '/teachers'
    | '/type'
    | '/user'
    | '/'
    | '/news/create'
    | '/pages/create'
    | '/menu'
    | '/news'
    | '/pages'
    | '/menu/view/$id'
    | '/news/update/$id'
    | '/pages/update/$id'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_auth/login'
    | '/_main/about'
    | '/_main/banner'
    | '/_main/categories'
    | '/_main/course'
    | '/_main/documents'
    | '/_main/event'
    | '/_main/faqs'
    | '/_main/feedbacks'
    | '/_main/leadership'
    | '/_main/links'
    | '/_main/media'
    | '/_main/partners'
    | '/_main/settings'
    | '/_main/teachers'
    | '/_main/type'
    | '/_main/user'
    | '/_main/'
    | '/_main/news/create'
    | '/_main/pages/create'
    | '/_main/menu/'
    | '/_main/news/'
    | '/_main/pages/'
    | '/_main/menu/view/$id'
    | '/_main/news/update/$id'
    | '/_main/pages/update/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user': {
      id: '/_main/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof MainUserRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/type': {
      id: '/_main/type'
      path: '/type'
      fullPath: '/type'
      preLoaderRoute: typeof MainTypeRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/teachers': {
      id: '/_main/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof MainTeachersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/settings': {
      id: '/_main/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof MainSettingsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/partners': {
      id: '/_main/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof MainPartnersRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/media': {
      id: '/_main/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MainMediaRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/links': {
      id: '/_main/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof MainLinksRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/leadership': {
      id: '/_main/leadership'
      path: '/leadership'
      fullPath: '/leadership'
      preLoaderRoute: typeof MainLeadershipRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/feedbacks': {
      id: '/_main/feedbacks'
      path: '/feedbacks'
      fullPath: '/feedbacks'
      preLoaderRoute: typeof MainFeedbacksRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/faqs': {
      id: '/_main/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof MainFaqsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/event': {
      id: '/_main/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof MainEventRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/documents': {
      id: '/_main/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof MainDocumentsRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/course': {
      id: '/_main/course'
      path: '/course'
      fullPath: '/course'
      preLoaderRoute: typeof MainCourseRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories': {
      id: '/_main/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainCategoriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/banner': {
      id: '/_main/banner'
      path: '/banner'
      fullPath: '/banner'
      preLoaderRoute: typeof MainBannerRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/about': {
      id: '/_main/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MainAboutRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_main/pages/': {
      id: '/_main/pages/'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof MainPagesIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/news/': {
      id: '/_main/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof MainNewsIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/menu/': {
      id: '/_main/menu/'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MainMenuIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/pages/create': {
      id: '/_main/pages/create'
      path: '/pages/create'
      fullPath: '/pages/create'
      preLoaderRoute: typeof MainPagesCreateRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/news/create': {
      id: '/_main/news/create'
      path: '/news/create'
      fullPath: '/news/create'
      preLoaderRoute: typeof MainNewsCreateRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/pages/update/$id': {
      id: '/_main/pages/update/$id'
      path: '/pages/update/$id'
      fullPath: '/pages/update/$id'
      preLoaderRoute: typeof MainPagesUpdateIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/news/update/$id': {
      id: '/_main/news/update/$id'
      path: '/news/update/$id'
      fullPath: '/news/update/$id'
      preLoaderRoute: typeof MainNewsUpdateIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/menu/view/$id': {
      id: '/_main/menu/view/$id'
      path: '/menu/view/$id'
      fullPath: '/menu/view/$id'
      preLoaderRoute: typeof MainMenuViewIdRouteImport
      parentRoute: typeof MainRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainAboutRoute: typeof MainAboutRoute
  MainBannerRoute: typeof MainBannerRoute
  MainCategoriesRoute: typeof MainCategoriesRoute
  MainCourseRoute: typeof MainCourseRoute
  MainDocumentsRoute: typeof MainDocumentsRoute
  MainEventRoute: typeof MainEventRoute
  MainFaqsRoute: typeof MainFaqsRoute
  MainFeedbacksRoute: typeof MainFeedbacksRoute
  MainLeadershipRoute: typeof MainLeadershipRoute
  MainLinksRoute: typeof MainLinksRoute
  MainMediaRoute: typeof MainMediaRoute
  MainPartnersRoute: typeof MainPartnersRoute
  MainSettingsRoute: typeof MainSettingsRoute
  MainTeachersRoute: typeof MainTeachersRoute
  MainTypeRoute: typeof MainTypeRoute
  MainUserRoute: typeof MainUserRoute
  MainIndexRoute: typeof MainIndexRoute
  MainNewsCreateRoute: typeof MainNewsCreateRoute
  MainPagesCreateRoute: typeof MainPagesCreateRoute
  MainMenuIndexRoute: typeof MainMenuIndexRoute
  MainNewsIndexRoute: typeof MainNewsIndexRoute
  MainPagesIndexRoute: typeof MainPagesIndexRoute
  MainMenuViewIdRoute: typeof MainMenuViewIdRoute
  MainNewsUpdateIdRoute: typeof MainNewsUpdateIdRoute
  MainPagesUpdateIdRoute: typeof MainPagesUpdateIdRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAboutRoute: MainAboutRoute,
  MainBannerRoute: MainBannerRoute,
  MainCategoriesRoute: MainCategoriesRoute,
  MainCourseRoute: MainCourseRoute,
  MainDocumentsRoute: MainDocumentsRoute,
  MainEventRoute: MainEventRoute,
  MainFaqsRoute: MainFaqsRoute,
  MainFeedbacksRoute: MainFeedbacksRoute,
  MainLeadershipRoute: MainLeadershipRoute,
  MainLinksRoute: MainLinksRoute,
  MainMediaRoute: MainMediaRoute,
  MainPartnersRoute: MainPartnersRoute,
  MainSettingsRoute: MainSettingsRoute,
  MainTeachersRoute: MainTeachersRoute,
  MainTypeRoute: MainTypeRoute,
  MainUserRoute: MainUserRoute,
  MainIndexRoute: MainIndexRoute,
  MainNewsCreateRoute: MainNewsCreateRoute,
  MainPagesCreateRoute: MainPagesCreateRoute,
  MainMenuIndexRoute: MainMenuIndexRoute,
  MainNewsIndexRoute: MainNewsIndexRoute,
  MainPagesIndexRoute: MainPagesIndexRoute,
  MainMenuViewIdRoute: MainMenuViewIdRoute,
  MainNewsUpdateIdRoute: MainNewsUpdateIdRoute,
  MainPagesUpdateIdRoute: MainPagesUpdateIdRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
