/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteRouteImport } from './routes/_main/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainUserRouteImport } from './routes/_main/user'
import { Route as MainMediaRouteImport } from './routes/_main/media'
import { Route as MainCategoriesRouteImport } from './routes/_main/categories'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthAuthRouteImport } from './routes/_auth/auth'

const MainRouteRoute = MainRouteRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainUserRoute = MainUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainMediaRoute = MainMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => MainRouteRoute,
} as any)
const MainCategoriesRoute = MainCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => MainRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/categories': typeof MainCategoriesRoute
  '/media': typeof MainMediaRoute
  '/user': typeof MainUserRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthAuthRoute
  '/login': typeof AuthLoginRoute
  '/categories': typeof MainCategoriesRoute
  '/media': typeof MainMediaRoute
  '/user': typeof MainUserRoute
  '/': typeof MainIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_main': typeof MainRouteRouteWithChildren
  '/_auth/auth': typeof AuthAuthRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_main/categories': typeof MainCategoriesRoute
  '/_main/media': typeof MainMediaRoute
  '/_main/user': typeof MainUserRoute
  '/_main/': typeof MainIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/auth' | '/login' | '/categories' | '/media' | '/user' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/login' | '/categories' | '/media' | '/user' | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/_main'
    | '/_auth/auth'
    | '/_auth/login'
    | '/_main/categories'
    | '/_main/media'
    | '/_main/user'
    | '/_main/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  MainRouteRoute: typeof MainRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MainRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/user': {
      id: '/_main/user'
      path: '/user'
      fullPath: '/user'
      preLoaderRoute: typeof MainUserRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/media': {
      id: '/_main/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MainMediaRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_main/categories': {
      id: '/_main/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof MainCategoriesRouteImport
      parentRoute: typeof MainRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/auth': {
      id: '/_auth/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthAuthRoute: typeof AuthAuthRoute
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAuthRoute: AuthAuthRoute,
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface MainRouteRouteChildren {
  MainCategoriesRoute: typeof MainCategoriesRoute
  MainMediaRoute: typeof MainMediaRoute
  MainUserRoute: typeof MainUserRoute
  MainIndexRoute: typeof MainIndexRoute
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainCategoriesRoute: MainCategoriesRoute,
  MainMediaRoute: MainMediaRoute,
  MainUserRoute: MainUserRoute,
  MainIndexRoute: MainIndexRoute,
}

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  MainRouteRoute: MainRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
